spring.application.name=transport
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:nl_transport}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:nltransport}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.thymeleaf.cache=false
